services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./app:/app
      - shared_tmp:/shared_tmp
    env_file: 
      - path: ".env"
        required: true
    restart: always

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
      
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: >
      watchmedo auto-restart 
      -d . 
      -R 
      -p '*.py' 
      --debug-force-polling 
      -- celery -A video_extractor.celery worker --loglevel=info -c 16
    volumes:
      - shared_tmp:/shared_tmp
    depends_on:
      - redis

volumes:
  shared_tmp: