start:
	docker compose -f docker-compose.yml up

build:
	docker compose -f docker-compose.yml up --build

detach:
	docker compose -f docker-compose.yml up --build -d

down:
	docker compose -f docker-compose.yml down

prod:
	docker compose -f docker-compose.prod.yml up --build

prod-down:
	docker compose -f docker-compose.prod.yml down